blank_issues_enabled: true
contact_links:
  - name: 質問・ディスカッション
    url: https://github.com/synthalpha/ai-game-sound-generator/discussions
    about: プロジェクトに関する質問や議論はこちら
  - name: ドキュメント
    url: https://github.com/synthalpha/ai-game-sound-generator/tree/main/docs
    about: プロジェクトのドキュメントはこちら