name: Deploy to Railway

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Railway
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          # Railway CLI をインストール
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Railway CLI のバージョン確認
          railway --version

          # 認証状態を確認し、必要に応じてログイン
          railway whoami || echo "Not authenticated, proceeding with token..."

          # プロジェクトIDを環境変数として設定してデプロイ
          export RAILWAY_PROJECT_ID=${{ secrets.RAILWAY_PROJECT_ID }}

          # デプロイ実行（サービス名を指定）
          railway up --service "${{ secrets.RAILWAY_SERVICE_NAME }}" --detach
