name: Deploy to Railway

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - production

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Railway
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "RAILWAY_ENVIRONMENT=production" >> $GITHUB_ENV
            echo "RAILWAY_SERVICE_NAME=ai-game-sound-generator" >> $GITHUB_ENV
          else
            echo "RAILWAY_ENVIRONMENT=development" >> $GITHUB_ENV
            echo "RAILWAY_SERVICE_NAME=dev-ai-game-sound-generator" >> $GITHUB_ENV
          fi

      - name: Install Railway CLI
        run: |
          # Railway CLIをインストール
          curl -fsSL https://railway.app/install.sh | sh

          # PATHを即座に更新
          export PATH="$HOME/.railway/bin:$PATH"

          # 確認
          which railway || echo "Railway not found in PATH"
          railway version || echo "Railway version check failed"

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
          AUTH_ENABLED: ${{ secrets.AUTH_ENABLED }}
          API_PORT: ${{ secrets.API_PORT }}
          APP_HOST: ${{ secrets.APP_HOST }}
          ELEVENLABS_BASE_URL: ${{ secrets.ELEVENLABS_BASE_URL }}
          ELEVENLABS_TIMEOUT: ${{ secrets.ELEVENLABS_TIMEOUT }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          API_WORKERS: ${{ secrets.API_WORKERS }}
          STORAGE_PATH: ${{ secrets.STORAGE_PATH }}
          CACHE_ENABLED: ${{ secrets.CACHE_ENABLED }}
          CACHE_TTL: ${{ secrets.CACHE_TTL }}
          APP_ENV: ${{ env.RAILWAY_ENVIRONMENT }}
        run: |
          # PATHを設定
          export PATH="$HOME/.railway/bin:$PATH"

          echo "Available Railway services:"
          RAILWAY_TOKEN="${{ secrets.RAILWAY_TOKEN }}" railway service list || echo "Failed to list services"

          echo ""
          echo "Attempting to deploy to: ${{ env.RAILWAY_SERVICE_NAME }}"

          # トークンとサービス名を指定してデプロイ
          RAILWAY_TOKEN="${{ secrets.RAILWAY_TOKEN }}" railway up --service "${{ env.RAILWAY_SERVICE_NAME }}" --detach
