name: Deploy to Railway

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - production

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Railway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "RAILWAY_ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "RAILWAY_ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # 環境別の環境変数設定
          if [[ "${{ env.RAILWAY_ENVIRONMENT }}" == "production" ]]; then
            # 本番環境
            railway variables --environment production \
              --set "APP_ENV=production" \
              --set "ELEVENLABS_API_KEY=${{ secrets.PROD_ELEVENLABS_API_KEY }}" \
              --set "AUTH_PASSWORD=${{ secrets.PROD_AUTH_PASSWORD }}" \
              --set "AUTH_ENABLED=${{ secrets.PROD_AUTH_ENABLED }}" \
              --set "API_PORT=${{ secrets.PROD_API_PORT }}" \
              --set "APP_HOST=${{ secrets.PROD_APP_HOST }}" \
              --set "ELEVENLABS_BASE_URL=${{ secrets.PROD_ELEVENLABS_BASE_URL }}" \
              --set "ELEVENLABS_TIMEOUT=${{ secrets.PROD_ELEVENLABS_TIMEOUT }}" \
              --set "LOG_LEVEL=${{ secrets.PROD_LOG_LEVEL }}" \
              --set "API_WORKERS=${{ secrets.PROD_API_WORKERS }}" \
              --set "STORAGE_PATH=${{ secrets.PROD_STORAGE_PATH }}" \
              --set "CACHE_ENABLED=${{ secrets.PROD_CACHE_ENABLED }}" \
              --set "CACHE_TTL=${{ secrets.PROD_CACHE_TTL }}"
          else
            # 開発環境
            railway variables --environment development \
              --set "APP_ENV=development" \
              --set "ELEVENLABS_API_KEY=${{ secrets.DEV_ELEVENLABS_API_KEY }}" \
              --set "AUTH_PASSWORD=${{ secrets.DEV_AUTH_PASSWORD }}" \
              --set "AUTH_ENABLED=${{ secrets.DEV_AUTH_ENABLED }}" \
              --set "API_PORT=${{ secrets.DEV_API_PORT }}" \
              --set "APP_HOST=${{ secrets.DEV_APP_HOST }}" \
              --set "ELEVENLABS_BASE_URL=${{ secrets.DEV_ELEVENLABS_BASE_URL }}" \
              --set "ELEVENLABS_TIMEOUT=${{ secrets.DEV_ELEVENLABS_TIMEOUT }}" \
              --set "LOG_LEVEL=${{ secrets.DEV_LOG_LEVEL }}" \
              --set "API_WORKERS=${{ secrets.DEV_API_WORKERS }}" \
              --set "STORAGE_PATH=${{ secrets.DEV_STORAGE_PATH }}" \
              --set "CACHE_ENABLED=${{ secrets.DEV_CACHE_ENABLED }}" \
              --set "CACHE_TTL=${{ secrets.DEV_CACHE_TTL }}"
          fi

          # デプロイ実行
          railway up --environment ${{ env.RAILWAY_ENVIRONMENT }}