name: Deploy to Railway

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'GitHub Environment name (must match exactly)'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.event_name == 'workflow_dispatch'
      && inputs.environment
      || (github.ref == 'refs/heads/main' && 'production' || 'development') }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI (non-interactive)
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy (uses Environment secrets)
        env:
          # ここで参照する secrets は「その Environment」にある必要があります
          RAILWAY_TOKEN:        ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID:   ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        run: |
          set -euo pipefail
          railway login --token "$RAILWAY_TOKEN"
          railway whoami

          [[ -n "${RAILWAY_PROJECT_ID:-}" ]]   || { echo "::error::RAILWAY_PROJECT_ID is empty"; exit 1; }
          [[ -n "${RAILWAY_SERVICE_NAME:-}" ]] || { echo "::error::RAILWAY_SERVICE_NAME is empty"; exit 1; }

          railway project get --project "$RAILWAY_PROJECT_ID" >/dev/null
          railway service get  --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE_NAME" >/dev/null

          railway up --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE_NAME" --detach
