name: Deploy to Railway

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - production

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Railway
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "RAILWAY_ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "RAILWAY_ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # 環境変数設定（Environmentから自動的に適切なSecretsが使用される）
          railway variables --environment ${{ env.RAILWAY_ENVIRONMENT }} \
            --set "APP_ENV=${{ env.RAILWAY_ENVIRONMENT }}" \
            --set "ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}" \
            --set "AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}" \
            --set "AUTH_ENABLED=${{ secrets.AUTH_ENABLED }}" \
            --set "API_PORT=${{ secrets.API_PORT }}" \
            --set "APP_HOST=${{ secrets.APP_HOST }}" \
            --set "ELEVENLABS_BASE_URL=${{ secrets.ELEVENLABS_BASE_URL }}" \
            --set "ELEVENLABS_TIMEOUT=${{ secrets.ELEVENLABS_TIMEOUT }}" \
            --set "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" \
            --set "API_WORKERS=${{ secrets.API_WORKERS }}" \
            --set "STORAGE_PATH=${{ secrets.STORAGE_PATH }}" \
            --set "CACHE_ENABLED=${{ secrets.CACHE_ENABLED }}" \
            --set "CACHE_TTL=${{ secrets.CACHE_TTL }}"

          # デプロイ実行
          railway up --environment ${{ env.RAILWAY_ENVIRONMENT }}